---
- name: Install postfix
  package:
    name: postfix
    state: present
  become: true

- name: Start postfix service
  service:
    name: postfix
    enabled: true
    state: started
  become: true
